### ISSUE TITLE
Filter Basic and Extended parts

### ISSUE THREAD

**Issue by besi** [yaqwsx/jlcparts#110]
When ordering with JLCPCB it's an financial advantage to use more basic parts.
https://jlcpcb.com/parts/basic_parts

Did you consider allowing people to filter those basic parts?
<img width="386" alt="Screenshot 2024-02-07 at 22 07 06" src="https://github.com/yaqwsx/jlcparts/assets/160412/b36a0ee8-eb8f-4fe7-b008-0fea3e4985bc">

**Comment by yaqwsx** [comment]
The filter is there since the project beginning:

![Screenshot from 2024-02-07 22-13-54](https://github.com/yaqwsx/jlcparts/assets/1590880/efd822f6-72d2-4cc7-9fd1-10ab117a81e8)

Or did I misunderstand your feature request?

**Comment by besi** [comment]
Very responsive. 
Thanks a lot.

**Comment by besi** [comment]
I was looking for all basic parts and did not understand that the filters only appear once there are some results being fetched. My bad.

BTW: There might be a small bug on your screenshot with the `[object Object]` in the list of options.
