### ISSUE TITLE
Display the low quantity fixed fee and/or attrition requirements.

### ISSUE THREAD

**Issue by sleemanj** [yaqwsx/jlcparts#13]
For low quantity of some parts, JLC assembly charges a fixed fee, these JLC minimum (eg 20 pieces for resistor is common) are not the same as LCSC minimum (eg 100 pieces for resistor is common).

![34](https://user-images.githubusercontent.com/207209/97862892-fd662200-1d6a-11eb-8beb-afdf2fc1e8ba.jpg)

Examples...

  * For qty≤20,charges a fixed fee $0.0380 https://jlcpcb.com/parts/componentSearch?searchTxt=0603WAF5101T5E 
  * For qty≤5,charges a fixed fee $3.8045   https://jlcpcb.com/parts/componentSearch?searchTxt=6TPE330ML 
  * For qty≤15,charges a fixed fee $0.2220 https://jlcpcb.com/parts/componentSearch?searchTxt=C20526

it would be good to have this JLC minimum shown in your tool with the pricing.

Also some parts have an attrition requirement, it would be useful to see this as well if the data is available, example below showing the attrition requirement for a part in the JLC quote process.

![33](https://user-images.githubusercontent.com/207209/97862216-d4915d00-1d69-11eb-9ea0-6f74febf11c7.jpg)

---
NB: Their explanation of attrition isn't great, it works like this... `Total_Parts_Charged = max( BOM + Attrition, MOQ ) * Price`

**Comment by yaqwsx** [comment]
Unfortunately, JLCPCB does not provide this information in their [component table](https://jlcpcb.com/componentSearch/uploadComponentInfo) where we source the data from.

To acquire the data, we either have to scrape the page or make requests from the client to the JLC website. Fortunately, the data are available via a GET request on the following URL:

```
https://jlcpcb.com/shoppingCart/smtGood/getComponentDetail?componentCode=C23186
```

It gives you JSON with these relevant keys:
```
"leastNumber": 20,
"leastNumberPrice": 0.0380,
"lossNumber": 6,
```

I won't be able to implement the functionality in the next two weeks.

**Comment by yaqwsx** [comment]
So the implementation is available at http://jlcparts-dev.honzamrazek.cz/. Could you test it and let me know if you spot any bugs? I will merge it to upstream if after I get your confirmation it works correctly.

**Comment by sleemanj** [comment]
I'm not seeing it, where should I be looking?

![35](https://user-images.githubusercontent.com/207209/98452951-e1bea980-21b8-11eb-873d-d7d15949a2f3.jpg)

**Comment by yaqwsx** [comment]
Try it again - there was a problem with CORS on the deployed page I didn't notice.

**Comment by sleemanj** [comment]
Works, but the calculation appears incorrect for the item I checked...

![36](https://user-images.githubusercontent.com/207209/98462921-9e962200-221c-11eb-9df0-1b92886053e9.jpg)

![37](https://user-images.githubusercontent.com/207209/98462923-9fc74f00-221c-11eb-919b-27bc74cefe55.jpg)

**Comment by yaqwsx** [comment]
Ouch, the quantity is sometimes returned as string and then Javascript concatenates instead of adding /o\. It should be fixed now.

**Comment by sleemanj** [comment]
Cool I checked some random ones and they seem ok to me :+1:

**Comment by yaqwsx** [comment]
Ok, so I deployed it on the main page.
