### ISSUE TITLE
Please add option to parse/understand voltage/current range.

### ISSUE THREAD

**Issue by AndKe** [yaqwsx/jlcparts#145]
Selecting all regulators that can handle >54v is  quite a task

![image](https://github.com/user-attachments/assets/123fdf5c-592c-4c90-bc97-05c844b5f8ae)

It would be very nice if one could search for ">50V"   or 1A , instead of manually selecting all the lines that fall within.

Thank you for a great tool.

**Comment by dougy83** [comment]
This is addressed in #126 
It is implemented in my test fork: [link](https://dougy83.github.io/jlcparts)

**Comment by AndKe** [comment]
please see: 
![image](https://github.com/user-attachments/assets/d1bf365a-e011-4432-a37e-4272eae9feda)

Why dont I see the range tool for - for example current ?  (looking for 2.2uH  3-5A)

**Comment by dougy83** [comment]
Range tool is only for attributes specified as ranges, e.g. 5V~24V, etc. The currents in your screenshot are single values, and sorted, so you can multi select from a start value to an end value using the shift key and clicking, as normal.

**Comment by AndKe** [comment]
Thank you!
