### ISSUE TITLE
Option to find inside the datasheets

### ISSUE THREAD

**Issue by jealcuna** [yaqwsx/jlcparts#21]
The filter provided by jlcpcb is not always complete, there are some features that only you can find reading the datasheet. So I think that is difficult to add new fields to find inside the all datasheets, hence should be easy if you add a search bar that will find inside of the datasheet of all components and only show the matched search

**Comment by yaqwsx** [comment]
This is similar to #17. I am not sure that the current technological solution could handle full-text search in such a big dataset. That's why #17 proposes only keyword/keysentences from the datasheet.

**Comment by yaqwsx** [comment]
Closing in favor of #17
