### ISSUE TITLE
nothing works

### ISSUE THREAD

**Issue by phil123456** [yaqwsx/jlcparts#23]
I tried searching for 10k 0603 ,nothing shows up
I tried clicking everywhere, nothing happens

**Comment by yaqwsx** [comment]
Hello phil. Thank you for your report, however, there a lot of information missing so I can reproduce the problem and fix it. 

Are you a first-time user? If so, you should follow the instructions in the yellow box that you should see:
![Screenshot from 2021-01-16 20-52-05](https://user-images.githubusercontent.com/1590880/104821555-00868f80-583d-11eb-82f2-2ff42b2e27ce.png)

If not, do you see a complete page? Did you try updating the library? Could you give me information about your browser and give me a screencast or at least a series of screenshots?

**Comment by yaqwsx** [comment]
There has been no response; closing. If the problem persists, please, supply more information and reopen the issue.
