### ISSUE TITLE
cors.bridged.cc requires a new API key, causing "Cannot fetch attrition data"

### ISSUE THREAD

**Issue by MURPHYENGINEERING** [yaqwsx/jlcparts#43]
See this issue for a resolution: https://github.com/gridaco/base/issues/23

The failing line is
https://github.com/yaqwsx/jlcparts/blob/39caf50af41fa042111a616fde2d1ff049228ff1/web/src/jlc.js#L23

The underlying error is

> Access to fetch at 'https://cors.bridged.cc/https://jlcpcb.com/shoppingCart/smtGood/selectSmtComponentList' from origin 'https://yaqwsx.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by yaqwsx** [comment]
Thank you for reporting. Fixed.
