### ISSUE TITLE
can this be made for apache webserver and not npm?

### ISSUE THREAD

**Issue by themindfactory** [yaqwsx/jlcparts#47]
is it easy, hard? I assume hard :-)

Thanks!

**Comment by yaqwsx** [comment]
I don't follow. What exactly do you want to achieve?

**Comment by themindfactory** [comment]
I have an Apache webserver running, I do not have NPM on the server, so was
hoping there would be a tweak to make it happy with Apache

Richard.

**Comment by yaqwsx** [comment]
The project is static website. It has no backend. You can use whatever software to serve it. The page is generated by a python script every day. That's it.
