### ISSUE TITLE
Fix URL with '?' character

### ISSUE THREAD

**Issue by eiffel31** [yaqwsx/jlcparts#49]
If you select category "Connectors" and then sub-category "Cold-pressed?Terminals".

Then all products will have an URL unable to access to the product on LCSC site.
Ex: 
https://lcsc.com/product-detail/Cold-pressed?Terminals_Temile-JNQ031_C499664.html
Replacing "?" by "%3F" solves the problem:
https://lcsc.com/product-detail/Cold-pressed%3FTerminals_Temile-JNQ031_C499664.html

Other category names with special character have even more severe problems. Ex : "Data Converters" -> "Analog Switches & Multiplexers". I don't know if it is related.

Thanks for the great tool!

**Comment by yaqwsx** [comment]
This was addressed in [c2750d8](https://github.com/yaqwsx/jlcparts/commit/c2750d85ed56368fc87e6418fddd951afb79db76). However, it will take a couple of days to propagate throughout the whole database as the links are generated only during the scraping stage and we cannot scrape the whole database at once.
