### ISSUE TITLE
[BUG] Quantity error: extra 0

### ISSUE THREAD

**Issue by eiffel31** [yaqwsx/jlcparts#55]
The quantity should be 1-9, 10-29, 30-99...
Unfortunately, it is displayed with an extra 0, giving 10-90, 100-290, 300-990...

It is not just a display formatting error, because price considered for 1000 pcs is calculated according to the wrong quantity value.

Another problem (may be related or not): the price is different from the price on the official website.

Example below shows product C2683482.

![image](https://user-images.githubusercontent.com/79512904/156721657-ff3847d7-04ce-4b88-a4a8-1db46f10c22e.png)
![image](https://user-images.githubusercontent.com/79512904/156722760-60bedcbb-2ff9-47c1-a8f3-3bf6a7b1a765.png)

**Comment by yaqwsx** [comment]
This is an inconsistency in data provided by JLC PCB obtained during the last update. Once we can update again, it should be working normally.

**Comment by yaqwsx** [comment]
Once updated everything seems to work fine:

![Screenshot from 2022-03-22 08-23-36](https://user-images.githubusercontent.com/1590880/159428696-622e30f7-e627-4f89-b68f-47784429a135.png)
