### ISSUE TITLE
Contact JLCPCB to merge this tool upstream?

### ISSUE THREAD

**Issue by Harvie** [yaqwsx/jlcparts#6]
Hello,
last time i needed some improvement in their search (asked them to add filtering parts by basic/extended) i just contacted them using website and they made it happen. Have you considered to offer your work to them?

**Comment by yaqwsx** [comment]
Well, this project is technically incompatible with their solutions and JLC PCB prefers to have an in-house solution. Already talked to them. It is much better to keep this project standalone.
