### ISSUE TITLE
"In Stock" filter

### ISSUE THREAD

**Issue by 2ftg** [yaqwsx/jlcparts#7]
Hello,

It would would be good to have an "In Stock" filter like on digikey and mouser. 
The current version allows sorting by the stock level, so that is pulled and those with stock of 0 might be filterable. 
JLCPCB parts library lives quite a bit and parts come and go, so the list has loads of parts that might never re-appear and having them in your search will just slow down one's work.

**Comment by yaqwsx** [comment]
Nice idea! Implemented in 55b1b0d and already online.
