### ISSUE TITLE
Where did you get access keys?

### ISSUE THREAD

**Issue by polkovnikov-ph** [yaqwsx/jlcparts#77]
Where do LCSC_KEY and LCSC_SECRET come from?

**Comment by polkovnikov-ph** [comment]
Duplicate to https://github.com/yaqwsx/jlcparts/issues/61

How did you contact them though?

**Comment by yaqwsx** [comment]
Via e-mail after they forced me to shut-down the service: https://blog.honzamrazek.cz/2022/03/jlcparts-rising-from-the-ashes/
