### ISSUE TITLE
Update component database fail

### ISSUE THREAD

**Issue by ElliotCui97** [yaqwsx/jlcparts#78]
look like update component database failed 5 days
![image](https://user-images.githubusercontent.com/49222891/204099182-d07bf55b-c21e-4815-af47-96209e0a42ff.png)

**Comment by yaqwsx** [comment]
Yes, I know. JLC PCB component table is out-of-service at the moment. This was reported, and there is nothing I can do about it. You can urge JLC PCB to fix their services.

**Comment by andylinpersonal** [comment]
![image](https://user-images.githubusercontent.com/26407395/204176080-b6c0ad51-ff88-4cf1-886b-7c10d6f59765.png)

They don't provide the link to the database now :(

**Comment by andylinpersonal** [comment]
![image](https://user-images.githubusercontent.com/26407395/204176580-c6088561-2881-4cee-b15e-332b5d39f65d.png)


They don't provide the link to the database now 👎🏻

**Comment by yaqwsx** [comment]
I tried discussing with JLC PCB and finding a compromise. But without success. Details in https://blog.honzamrazek.cz/2022/12/jlcparts-falling-down-to-ashes/.

**Comment by PhilCS** [comment]
JLC is working on an API for KiCad plugin devs, maybe your search engine can be adapted to it once available: https://github.com/Bouni/kicad-jlcpcb-tools/issues/241#issuecomment-1367159022

**Comment by yaqwsx** [comment]
I am in close touch with JLC, and I initiated their interested in developing API. However, at the moment it doesn't do what we need. I hope we can get the catalog back working late in January or early in February.

**Comment by yaqwsx** [comment]
The service should be back operational via [3da7afa](https://github.com/yaqwsx/jlcparts/commit/3da7afa003f11d1251286e85e4c7b3d486efd722). We still need to implement #37 and we miss minimal order quantity and attrition info, as JLC PCB no longer provides them, though. But better than nothing.

**Comment by PhilCS** [comment]
Cheers mate!
