### ISSUE TITLE
add an easy way to remove a column

### ISSUE THREAD

**Issue by tenbaht** [yaqwsx/jlcparts#8]
When searching for an MCU I added the column "Program Memory Type". Now I am looking for LEDs and that column is still there. It would be useful to have an easy way to remove it without changing back to the MCU selection. Something like a simple "X" button like in a web browser for closing a tab.
Automatic removal of inactive columns would be possible, but that might be annoying if someone keeps going back and forth between different search topics.

**Comment by yaqwsx** [comment]
Good idea! Implemented in 2352011 and already online.
