### ISSUE TITLE
Stock is not displayed

### ISSUE THREAD

**Issue by muhlpachr** [yaqwsx/jlcparts#92]
![image](https://github.com/yaqwsx/jlcparts/assets/708522/4c7d194e-72e7-400b-9f32-472bfe36c72f)

**Comment by yaqwsx** [comment]
Could you provide more details - e.g., precise query, system, and browser used? And also include any errors shown in the developer's console.

I just tested a query that includes that component you have shown in your  screenshot, and it seems to work just fine:
![Screenshot from 2023-08-17 07-04-54](https://github.com/yaqwsx/jlcparts/assets/1590880/167d90f9-80e0-4dae-9475-f383b5e34830)

**Comment by muhlpachr** [comment]
Query was LDO, it works fine now.
Thank you.
