### ISSUE TITLE
question: cache.sqlite3

### ISSUE THREAD

**Issue by ole00** [yaqwsx/jlcparts#93]
Hi,
I like the cache.sqlite3 file I downloaded from github.io (linked in your readme.md). It seems to be a bit out of date now (the timestamps seem to be from May 2023). How do I generate new cache file?  Or is it generated when the web page collects  the data? If so, where is the cache file located? Thank you.

**Comment by yaqwsx** [comment]
Where did you download that file? The file was last updated 14 hours ago.

**Comment by ole00** [comment]
From the link in readme.md :
wget https://yaqwsx.github.io/jlcparts/data/cache.zip 
.. and other zip parts: *.z01, *.z02 etc.

The time stamps in that file looks to be: 1682999876 (Tuesday, 2 May 2023 03:57:56).  I assume it is the timestamp of "last_update INTEGER NOT NULL" field.

**Comment by yaqwsx** [comment]
The file should be updated in this run: https://github.com/yaqwsx/jlcparts/actions/runs/6044971793

**Comment by ole00** [comment]
I see. The component_table artefact is quite helpful as well - thanks for that link. I'll use it instead of the caches.sqlite3.

**Comment by ole00** [comment]
Closing the issue. Thanks for your help.

**Comment by ole00** [comment]
FYI, I've created a KiCad BOM exporter that selects basic parts from the LCSC database and assigns them to Resistors and Capacitors. This can be helpful if the KiCad project has plenty of standard value resistors and capacitors. The BOM exporter uses filtered data from the parts.csv file as produced by this repo.
The project sources and tools are hosted here: https://github.com/ole00/kicad_bom_jlcpcb_auto
